feat: pass custom type for any asssets with phoenix bodytype
readyplayerme/content-validation-schemas pull request #34
Opened 2024-10-10 11:08 UTC by rk132

2024-10-16 12:10 UTC, Olaf-Wolf3D requested changes

2024-10-16 12:10 UTC, Olaf-Wolf3D commented on schemas/gltf-asset.schema.json
> +      "default": "custom",
It is a bit confusing that the default value "custom" for bodyType does not trigger the custom asset schema (assetCustom), but the regular asset types. Which schema should the default value trigger?

2024-10-16 12:10 UTC, Olaf-Wolf3D commented on schemas/gltf-asset.schema.json
> +        "type": "Bodytype should be a string."
Please add a space between Body and type, the it matches with assetType error message.

2024-10-16 17:01 UTC, Olaf-Wolf3D approved these changes
If this is tested and made sure that regular assets still upload in studio 1.0 asset manager, this can be merged.

2024-10-17 11:47 UTC, merged

2024-10-17 11:48 UTC, MaxAndreassenRPM commented
Merged as per this thread -> https://readyplayerme.slack.com/archives/C042V5Q9HK9/p1729165561063299?thread_ts=1728564057.961929&cid=C042V5Q9HK9